import * as TablerIcons from '@tabler/icons-vue';
import {
  IconApi,
  IconArrowsDiff,
  IconBolt,
  IconBrandAngular,
  IconBrandAstro,
  IconBrandAws,
  IconBrandAzure,
  IconBrandBootstrap,
  IconBrandCloudflare,
  IconBrandCss3,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGit,
  IconBrandGithub,
  IconBrandGitlab,
  IconBrandGolang,
  IconBrandGraphql,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandLaravel,
  IconBrandMongodb,
  IconBrandMysql,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandNuxt,
  IconBrandPhp,
  IconBrandPnpm,
  IconBrandPrisma,
  IconBrandPython,
  IconBrandReact,
  IconBrandSass,
  IconBrandSlack,
  IconBrandSupabase,
  IconBrandSvelte,
  IconBrandSwift,
  IconBrandTailwind,
  IconBrandTypescript,
  IconBrandVercel,
  IconBrandVite,
  IconBrandVscode,
  IconBrandVue,
  IconBrandWordpress,
  IconBrandYarn,
  IconCpu,
  IconDatabase,
  IconServer2,
} from '@tabler/icons-vue';
import type { Component } from 'vue';

const IconBrandJira = (TablerIcons as { IconBrandJira?: Component }).IconBrandJira ?? IconBolt;

const TABLER_ICON_MAP: Record<string, Component> = {
  IconApi,
  IconArrowsDiff,
  IconBolt,
  IconBrandAngular,
  IconBrandAstro,
  IconBrandAws,
  IconBrandAzure,
  IconBrandBootstrap,
  IconBrandCloudflare,
  IconBrandCss3,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGit,
  IconBrandGithub,
  IconBrandGitlab,
  IconBrandGolang,
  IconBrandGraphql,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandJira,
  IconBrandKotlin,
  IconBrandLaravel,
  IconBrandMongodb,
  IconBrandMysql,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandNuxt,
  IconBrandPhp,
  IconBrandPnpm,
  IconBrandPrisma,
  IconBrandPython,
  IconBrandReact,
  IconBrandSass,
  IconBrandSlack,
  IconBrandSupabase,
  IconBrandSvelte,
  IconBrandSwift,
  IconBrandTailwind,
  IconBrandTypescript,
  IconBrandVercel,
  IconBrandVite,
  IconBrandVscode,
  IconBrandVue,
  IconBrandWordpress,
  IconBrandYarn,
  IconDatabase,
  IconServer2,
};

export function resolveTablerIcon(iconName?: string | null): Component {
  if (!iconName) {
    return IconCpu;
  }

  const candidate = TABLER_ICON_MAP[iconName];
  return candidate ?? IconCpu;
}
